name: Build

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - feature/ppc64le-support
    tags:
      - v*

# permissions are needed if pushing to ghcr.io
permissions: 
  packages: write

jobs:
  build:
    if: github.repository == 'opf/openproject'
    runs-on: ubuntu-latest
    env:
      INPUT_BUILDOPTIONS: --pull
    steps:
      # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/docker/setup-qemu-action
      - name: Prepare docker files
        run: |
          cp ./docker/prod/Dockerfile ./Dockerfile
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          context: workflow
          images: |
            opf/openproject
          # Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      # Next build each architecture one after another.
      #
      # We cannot build all images at the same time
      # since during the build a postgres db is started
      # which will fail for all but 1 of the builds
      # due to sockets being shared on the docker host.
      - name: Build and push amd64
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push arm
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm/v7
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push ppc64
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/ppc64le
          pull: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
