name: "Test suite"
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests
on:
  push:
    branches:
      - dev
      - release/*
    paths-ignore:
      - 'docs/**'
      - 'help/**'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - 'docs/**'
      - 'help/**'
      - 'packaging/**'
      - '.pkgr.yml'

permissions:
  contents: read

jobs:
  all:
    name: Units + Features
    if: github.repository == 'opf/openproject'
    runs-on: [self-hosted, scaleway, docker, x64, XL]
    timeout-minutes: 60
    env:
      CI_CACHE_PATH: "/tmp/cache"
      LOCAL_DEV_CHECK: 1
      CI_RETRY_COUNT: 3
      CAPYBARA_AWS_ACCESS_KEY_ID: "${{ secrets.CAPYBARA_AWS_ACCESS_KEY_ID }}"
      CAPYBARA_AWS_SECRET_ACCESS_KEY: "${{ secrets.CAPYBARA_AWS_SECRET_ACCESS_KEY }}"
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: cache
      uses: actions/cache@v3
      with:
        path: /tmp/cache
        key: ${{ runner.os }}-ruby32-core-tests-all-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-ruby32-core-tests-all-
          ${{ runner.os }}-ruby32-core-tests-
    - name: build
      run: docker-compose -f docker-compose.ci.yml build ci
    - name: test
      run: docker-compose -f docker-compose.ci.yml run ci setup-tests run-units run-features
    - name: cleanup
      if: ${{ always() }}
      run: |
        docker-compose -f docker-compose.ci.yml down --remove-orphans -t 10
        sudo chown -R $(whoami):$(id -ng) $CI_CACHE_PATH
  api-spec:
    name: APIv3 specification (OpenAPI 3.0)
    if: github.repository == 'opf/openproject'
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: ./script/api/validate_spec
